# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7918c78a740b23dfae8c41df57ca036a463aa88d323f488641fb52b403218bbe97b08fc80b56a67eb47b17ae2a23d568a3a7357d9dd55a0f82ce8f67fa944357

test:
  secret_key_base: 354bbe07445633dc70a6b380b8307ad3eb3ac2a46288b3ed0402e088fc0a9ea83ccfd8b6522b108c81eb02926462a46a4c14e69c891398fc9eb85ea26a011460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7918c78a740b23dfae8c41df57ca036a463aa88d323f488641fb52b403218bbe97b08fc80b56a67eb47b17ae2a23d568a3a7357d9dd55a0f82ce8f67fa944357

